set_list = {'Alpha', 'Bravo', 'Charllie'}
print('1:',set_list)
set_list.add('Delta')
print('1:',set_list)
set2_list = set_list.copy()
print('2:',set2_list)
set2_list.pop()
print('2:',set2_list)
set2_list.pop()
print('2:',set2_list)
print('1:',set_list)
intersection = set_list.intersection(set2_list)
print('int:',intersection)
print('2:',set2_list)
print('1:',set_list)
set2_list.pop()

print('1:',set_list)
print('2:', set2_list)
difference = set_list.difference(set2_list)
print(difference)
